apiVersion: apps/v1
kind: Deployment
metadata:
  name: standingsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standingsapp
  template:
    metadata:
      labels:
        app: standingsapp
    spec:
      containers:
        - name: standingsapp
          image: radosz365/standingsapp:latest
          ports:
            - containerPort: 80
          redinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
